spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    user: local_dev
    password: imgarena
    schemas: licensed_tennis_matches

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org:
      springframework:
        web: DEBUG